# Site settings
title: "Ailton Martinez"
email: ailtonmtz@gmail.com
description: "My primer blog personal"
baseurl: ""
url: "https://ailtonmz.github.io/"
title_description: "Bienvenido a mi blog Soy un estudiante con sólidos conocimientos en cloud computing y sus diferentes áreas específicas: servidores, base de datos, mejoramiento y mantenimiento de sistemas, así como en fundamentos administrativos."
title_image: "https://scontent.fver2-1.fna.fbcdn.net/v/t39.30808-6/273994435_1683542191977732_7005859142379511699_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeGweaWQ2DD2PweCb5iMQJlcUe5Ua7TTrz5R7lRrtNOvPrjQVGFtXL2F-SxUx6S8ekZ8_3rw_dk_N9pgztnvrNI6&_nc_ohc=lxQAuanJYpAAX8r0JxB&_nc_ht=scontent.fver2-1.fna&oh=00_AT86wrORXRA9Rki_MegcmIDQHwWBiet4xQC5IjvJqQwM-Q&oe=62443FDD"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/ailtonmz/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  ailtonmz
instagram_username: 
reddit_username: 
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link: https://www.facebook.com/ailton.hernandez.10/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
