# Site settings
title: "Ailton Martinez"
email: ailtonmtz@gmail.com
description: "My primer blog personal"
#baseurl: ""
url: "https://ailtonmz.github.io/"
title_description: "Bienvenido a mi blog personal, disfruta de tu estadia."
title_image: "https://avatars.githubusercontent.com/u/102365402?s=400&u=2b8a74c891b6e957bb37dfb7aa42ac76794a3512&v=4"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/ailtonmz/ailtonmz.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  ailtonmz
instagram_username: 
reddit_username: 
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
