# Site settings
title: "Ailton Mtz"
email: ailtonmtz@gmail.com
description: "My blog personal"
#baseurl: ""
url: "https://ailtonmz.github.io/"
title_description: "Los retos son regalos que nos obligan a buscar un nuevo centro de gravedad. No luches contra ellos. Simplemente encuentra una nueva forma de mantenerte en pie."
title_image: "assets/mifoto.jpg"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/ailtonmz/ailtonmz.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 9

# Social usernames/URLs
#twitter_username: _jacobtomlinson
github_username:  ailtonmz
instagram_username: 
#reddit_username: 
linkedin_link: https://ailtonmz.github.io/
#google_plus_link: https://ailtonmz.github.io/
#stackoverflow_link: https://ailtonmz.github.io/
#xing_link:
facebook_link: https://www.facebook.com/ailton.hernandez.10

# Footer
footer_left: "Por <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/ailtonmz\">AiltonMartinez</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
